/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  safelist: [
    "bg-mint",
    "bg-blue",
    "bg-purple",
    "bg-coral",
    "bg-yellow",
    "bg-mint/70",
    "bg-blue/70",
    "bg-purple/70",
    "bg-coral/70",
    "bg-yellow/80",
    "bg-mint/10",
    "bg-blue/10",
    "bg-purple/10",
    "bg-coral/10",
    "bg-yellow/10",
    "bg-mint/20",
    "bg-blue/20",
    "bg-purple/20",
    "bg-coral/20",
    "bg-yellow/20",
    "bg-mint/15",
    "bg-blue/15",
    "bg-purple/15",
    "bg-coral/15",
    "bg-yellow/15",
    "bg-mint/25",
    "bg-blue/25",
    "bg-purple/25",
    "bg-coral/25",
    "bg-yellow/25",
    "border-mint/25",
    "border-blue/25",
    "border-purple/25",
    "border-coral/25",
    "border-yellow/30",
    "ring-mint/20",
    "ring-blue/20",
    "ring-purple/20",
    "ring-coral/20",
    "ring-yellow/25",
    "text-mint",
    "text-blue",
    "text-purple",
    "text-coral",
    "text-yellow",
  ],
  theme: {
    extend: {
      colors: {
        mint: "#4CC9A0",
        blue: "#5B8DEF",
        purple: "#A78BFA",
        coral: "#FF7D7D",
        yellow: "#FFC857",
        ink: "#0F172A",
        sub: "#64748B",
        bg: "#FFFFFF",
      },
      boxShadow: {
        soft: "0 18px 45px rgba(30, 42, 62, 0.10)",
        lift: "0 12px 26px rgba(91, 141, 239, 0.16)",
        card: "0 8px 24px rgba(15, 23, 42, 0.07)",
        tab: "0 -10px 28px rgba(15, 23, 42, 0.08)",
      },
      fontFamily: {
        sans: [
          "Pretendard",
          "Apple SD Gothic Neo",
          "Noto Sans KR",
          "Inter",
          "system-ui",
          "sans-serif",
        ],
      },
    },
  },
  plugins: [],
};
